# Generated by Django 5.2.15 on 2026-07-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snap", "0002_guest_phone_drop_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="password_hash",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=256
            ),
        ),
    ]
